*link:lang/de/README.de.adoc[Deutsch],
link:lang/es/README.es.adoc[Español],
link:lang/fr/README.fr.adoc[Français],
link:lang/zh-cn/README.zh-cn.adoc[简体中文],
link:lang/zh-tw/README.zh-tw.adoc[正體中文]*

= UML diagrams for Zim

This https://zim-wiki.org[Zim] plugin allows you to insert a UML diagram in a page.

It relies on http://plantuml.com[PlantUML] which, like http://graphviz.org[GraphViz], lets you write diagrams using a script language.

== Installation

* Install PlantUML using your usual package manager.

TIP: Use https://brew.sh[Homebrew] with macOS or https://scoop.sh[Scoop] with Windows. These tools are quick to set up and don’t require administrator rights.

* Open the plugins folder. In Zim, go to *Edit* > *Preferences* > *Plugins* tab and click on the *Open plugins folder* button.
* Download the link:umldiagrameditor.py[] file and move it to that folder.
* Restart Zim.
* In *Edit* > *Preferences* > *Plugins* tab, you can now tick *☐ Insert UML diagram*.
    * If you want to spice up your plantuml style with some style sheets, you can configure the base dir for looking for those files
    * See https://gist.github.com/jerieljan/4c82515ff5f2b2e4dd5122d354a82b7e[here] for an example

== Acknowledgements

This plugin is adapted from https://github.com/rolfkleef/zim-plantuml[Rolf Kleef's zim-plantuml] plugin and https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/master/zim/plugins/ditaaeditor.py[Yao-Po Wang's ditaaeditor.py] plugin.

Thanks to their respective authors.

* the default plantuml styles shipped are from https://gist.github.com/jerieljan/4c82515ff5f2b2e4dd5122d354a82b7e[Jeriel Jan del Prado ]