*link:../../lang/de/README.de.adoc[Deutsch],
link:../../README.adoc[English],
link:../../lang/es/README.es.adoc[Español],
link:../../lang/zh-cn/README.zh-cn.adoc[简体中文],
link:../../lang/zh-tw/README.zh-tw.adoc[正體中文]*

= Diagrammes UML pour Zim

Ce plugin pour https://zim-wiki.org[Zim] vous permet d’insérer des diagrammes UML dans une page.

Il repose sur http://plantuml.com[PlantUML] qui, à l’image de https://graphviz.org[GraphViz], permet de dessiner des diagrammes avec un script.

== Installation

* Installez PlantUML à l’aide de votre gestionnaire de paquets habituel.

TIP: Utilisez https://brew.sh[Homebrew] pour macOS ou https://scoop.sh[Scoop] pour Windows. Ces outils sont rapides à installer et ne requièrent pas de droits d’administrateur.

* Ouvrez le dossier des plugins. Dans Zim, allez dans *Édition* > *Préférences* > onglet *Plugins* et cliquez sur le bouton *Ouvrir le dossier des plugins*.
* Téléchargez le fichier link:umldiagrameditor.fr.py[] et déplacez-le dans ce dossier.
* Relancez Zim.
* Dans *Édition* > *Préférences* > onglet *Plugins*, vous pouvez désormais cocher *☐ Insérer un diagramme UML*.

== Remerciements

Ce plugin est une adaptation de https://github.com/rolfkleef/zim-plantuml[zim-plantuml
 de Rolf Kleef] et de https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/master/zim/plugins/ditaaeditor.py[ditaaeditor.py de Yao-Po Wang].

Merci à leurs auteurs respectifs.

