*link:../../lang/de/README.adoc[Deutsch],
link:../../README.adoc[English],
link:../../lang/fr/README.adoc[français],
link:../../lang/zh-cn/README.adoc[简体中文],
link:../../lang/zh-tw/README.adoc[正體中文]*

= Diagramas UML para Zim

Este plugin para https://zim-wiki.org[Zim] le permite insertar diagramas UML en una página.

Se basa en http://plantuml.com[PlantUML] que, como https://graphviz.org[GraphViz], le permite dibujar diagramas con un script.

== Instalación

* Instale PlantUML usando su gestor de paquetes habitual.

TIP: Use https://brew.sh[Homebrew] para macOS o https://scoop.sh[Scoop] para Windows. Estas utilidades se instalan rápidamente y no requieren derechos de administrador.

* Abra la carpeta de plugins. En Zim, vaya a *Editar* > *Preferencias* > pestaña *Extensiones* y haga clic en el botón *Abrir carpeta de plugins*.
* Descargue el archivo link:umldiagrameditor.py[] y muévalo a esta carpeta.
* Reinicia Zim.
* En *Editar* > *Preferencias* > pestaña *Extensiones*, ahora puede marcar *☐ Insertar diagrama UML*.

== Agradecimientos

Este plugin es una adaptación de https://github.com/rolfkleef/zim-plantuml[zim-plantuml de Rolf Kleef] y https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/master/zim/plugins/ditaaeditor.py[ditaaeditor.py de Yao-Po Wang].

Gracias a sus respectivos autores.

